package controller

import (
	"context"
	"fmt"
	"sync"
	"time"

	"sensor_logger/models"
)

// DataFusionController sets up the global synchronizer loops and distributes
// the incoming data to the active RealTimeData window.
type DataFusionController struct {
	// Our active window array handling
	currentWindow *models.RealTimeData
	windowMutex   sync.Mutex
	windowSize    time.Duration

	cameraDataChan chan models.CameraFrame
	// other sensors here ...
}

func NewDataFusionController(windowSize time.Duration) *DataFusionController {
	now := time.Now().UTC()
	return &DataFusionController{
		currentWindow:  models.NewRealTimeData(now, windowSize),
		windowSize:     windowSize,
		cameraDataChan: make(chan models.CameraFrame, 500), // Buffer to handle spikes
	}
}

// StartWindowRotator starts a background task that pushes old windows
// to SSD and creates a new memory instance based on the timeframe size dynamically.
func (f *DataFusionController) StartWindowRotator(ctx context.Context, wg *sync.WaitGroup) {
	defer wg.Done()

	// A ticker that triggers whenever the window size elapsed
	ticker := time.NewTicker(f.windowSize)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			fmt.Println("[DataFusionController] Shutting down window rotator...")
			_ = f.currentWindow.FlushToSSD()
			return
		case t := <-ticker.C:
			// Time to cycle to the next window!
			f.windowMutex.Lock()

			// 1. Copy over the finished old object reference
			oldWindow := f.currentWindow

			// 2. Initialize a fresh new slice array space for incoming reads
			// Ensures current ticks match precisely
			f.currentWindow = models.NewRealTimeData(t.UTC(), f.windowSize)

			f.windowMutex.Unlock()

			// 3. Flush the old slice instance to disk/SSD asynchronously
			go func(completedData *models.RealTimeData) {
				_ = completedData.FlushToSSD()
				// Slice is wiped in FlushToSSD, ready for GC.
			}(oldWindow)
		}
	}
}

// StartIngestListeners reads from the channels generated by camera_controller,
// lidar, etc., and injects them into the CURRENT timeframe data array dynamically.
// Global time synchronization relies on `Timestamp` being attached at the `_service` level.
func (f *DataFusionController) StartIngestListeners(ctx context.Context, wg *sync.WaitGroup) {
	defer wg.Done()

	for {
		select {
		case <-ctx.Done():
			fmt.Println("[DataFusionController] Stopping data ingest multiplexers...")
			return
		case data := <-f.cameraDataChan:
			// Inject into the currently tracked window structure
			f.windowMutex.Lock()

			if f.currentWindow.IsInWindow(data.Timestamp) {
				f.currentWindow.AddCameraFrame(data)
			} else {
				// We can have sophisticated logic here to buffer it for the next window
				// or store if slightly late
				fmt.Printf("[DataFusionController] Frame dropped: timestamp %v out of current window [%v - %v]\n",
					data.Timestamp.Format(time.Kitchen),
					f.currentWindow.StartTime.Format(time.Kitchen),
					f.currentWindow.EndTime.Format(time.Kitchen))
			}
			f.windowMutex.Unlock()
		}
	}
}

// GetCameraChannel permits external controllers to feed into the fusion queue
func (f *DataFusionController) GetCameraChannel() chan<- models.CameraFrame {
	return f.cameraDataChan
}
